# Generated by Django 4.2.17 on 2024-12-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horoscope", models.CharField(max_length=50)),
                ("travel_paragraph", models.TextField()),
                ("finance_paragraph", models.TextField()),
                ("education_paragraph", models.TextField()),
                ("travel_image", models.ImageField(upload_to="recommendations/")),
                ("finance_image", models.ImageField(upload_to="recommendations/")),
                ("education_image", models.ImageField(upload_to="recommendations/")),
            ],
        ),
        migrations.CreateModel(
            name="PunditBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("date_of_birth", models.DateField()),
                ("horoscope", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="VenueBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue_name", models.CharField(max_length=100)),
                ("booking_date", models.DateField()),
                ("event_type", models.CharField(max_length=100)),
                ("user_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
