# Generated by Django 4.2.17 on 2025-01-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_personalrecommendation_education_paragraph_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="punditbooking",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="punditbooking",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="punditbooking",
            name="horoscope",
        ),
        migrations.AddField(
            model_name="punditbooking",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="punditbooking",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="punditbooking",
            name="detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="punditbooking",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("housewarming", "Housewarming"),
                    ("wedding", "Wedding"),
                    ("satyanarayan_pooja", "Satyanarayan Pooja"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="punditbooking",
            name="samagri",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=10,
                null=True,
            ),
        ),
    ]
