# Generated by Django 4.2.17 on 2025-01-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_punditbooking_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venuebooking",
            name="booking_date",
        ),
        migrations.RemoveField(
            model_name="venuebooking",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="venuebooking",
            name="user_name",
        ),
        migrations.RemoveField(
            model_name="venuebooking",
            name="venue_name",
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="additional_request",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="number_of_guests",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="venuebooking",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="venuebooking",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wedding", "Wedding"),
                    ("party", "Party"),
                    ("conference", "Conference"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
