# Generated by Django 4.2.17 on 2025-01-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_venuebooking_booking_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "starting_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
