# Generated by Django 4.2.17 on 2025-01-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_banquet"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuebooking",
            name="banquet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.banquet",
            ),
        ),
    ]
