# Generated by Django 4.2.17 on 2025-01-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_venuebooking_banquet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venuebooking",
            name="name",
        ),
        migrations.AlterField(
            model_name="venuebooking",
            name="banquet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venue_bookings",
                to="core.banquet",
            ),
        ),
    ]
