# Generated by Django 4.2.17 on 2025-01-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_enquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.CharField(
                choices=[
                    ("Panna", "Panna"),
                    ("Pushparaj", "Pushparaj"),
                    ("Rudraksha", "Rudraksha"),
                ],
                max_length=255,
            ),
        ),
    ]
