# Generated by Django 4.2.17 on 2025-01-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_order_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pundit",
            name="image_url",
        ),
        migrations.AddField(
            model_name="pundit",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.CharField(
                choices=[
                    ("Panna", "Panna"),
                    ("Pushaparaj", "Pushaparaj"),
                    ("Rudraksha", "Rudraksha"),
                ],
                max_length=255,
            ),
        ),
    ]
