# Generated by Django 4.2.17 on 2025-01-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_pundit_image_url_pundit_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pundit",
            name="image",
        ),
        migrations.AddField(
            model_name="pundit",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
