# Generated by Django 4.2.17 on 2025-01-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_pundit_image_pundit_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pundit",
            name="image_url",
        ),
    ]
